#ifndef CONFIG_H
#define CONFIG_H

// Board configuration
#ifndef BOARD_NAME
#define BOARD_NAME "${this.board}"
#endif
#ifndef ui_imgset_
#define ui_imgset_ (NULL)
#endif
#ifndef CORE_DEBUG_LEVEL
#define CORE_DEBUG_LEVEL ARDUHAL_LOG_LEVEL_WARN
#endif

#ifndef BOARD_HAS_PSRAM
#define BOARD_HAS_PSRAM
#endif

#ifndef ARDUINO_ESP32S3_DEV
#define ARDUINO_ESP32S3_DEV
#endif

#ifndef CONFIG_SPIRAM_USE_CAPS_ALLOC
#define CONFIG_SPIRAM_USE_CAPS_ALLOC 1
#endif

#ifndef CONFIG_SPIRAM_USE_MALLOC
#define CONFIG_SPIRAM_USE_MALLOC 1
#endif

#ifndef CONFIG_FREERTOS_USE_TRACE_FACILITY
#define CONFIG_FREERTOS_USE_TRACE_FACILITY 1
#endif

#ifndef CONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS
#define CONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS 1
#endif

// Display configuration
#ifndef DISPLAY_WIDTH
#define DISPLAY_WIDTH 800
#endif

#ifndef DISPLAY_HEIGHT
#define DISPLAY_HEIGHT 480
#endif

#ifndef DISPLAY_BUS_SPEED
#define DISPLAY_BUS_SPEED 20000000
#endif

#ifndef CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240
#define CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240 1
#endif

#ifndef CONFIG_ESP32S3_SPIRAM_SUPPORT
#define CONFIG_ESP32S3_SPIRAM_SUPPORT 1
#endif

#ifndef DISPLAY_BCKL
#define DISPLAY_BCKL 2
#endif

// ST7262 Panel configuration
#ifndef ST7262_PANEL_CONFIG_HSYNC
#define ST7262_PANEL_CONFIG_HSYNC 39
#endif

#ifndef ST7262_PANEL_CONFIG_VSYNC
#define ST7262_PANEL_CONFIG_VSYNC 40
#endif

#ifndef ST7262_PANEL_CONFIG_DE
#define ST7262_PANEL_CONFIG_DE 41
#endif

#ifndef ST7262_PANEL_CONFIG_PCLK
#define ST7262_PANEL_CONFIG_PCLK 42
#endif

#ifndef ST7262_PANEL_CONFIG_DATA_R0
#define ST7262_PANEL_CONFIG_DATA_R0 15
#endif

#ifndef ST7262_PANEL_CONFIG_DATA_R1
#define ST7262_PANEL_CONFIG_DATA_R1 7
#endif

#ifndef ST7262_PANEL_CONFIG_DATA_R2
#define ST7262_PANEL_CONFIG_DATA_R2 6
#endif

#ifndef ST7262_PANEL_CONFIG_DATA_R3
#define ST7262_PANEL_CONFIG_DATA_R3 5
#endif

#ifndef ST7262_PANEL_CONFIG_DATA_R4
#define ST7262_PANEL_CONFIG_DATA_R4 4
#endif

#ifndef ST7262_PANEL_CONFIG_DATA_G0
#define ST7262_PANEL_CONFIG_DATA_G0 9
#endif

#ifndef ST7262_PANEL_CONFIG_DATA_G1
#define ST7262_PANEL_CONFIG_DATA_G1 46
#endif

#ifndef ST7262_PANEL_CONFIG_DATA_G2
#define ST7262_PANEL_CONFIG_DATA_G2 3
#endif

#ifndef ST7262_PANEL_CONFIG_DATA_G3
#define ST7262_PANEL_CONFIG_DATA_G3 8
#endif

#ifndef ST7262_PANEL_CONFIG_DATA_G4
#define ST7262_PANEL_CONFIG_DATA_G4 16
#endif

#ifndef ST7262_PANEL_CONFIG_DATA_G5
#define ST7262_PANEL_CONFIG_DATA_G5 1
#endif

#ifndef ST7262_PANEL_CONFIG_DATA_B0
#define ST7262_PANEL_CONFIG_DATA_B0 14
#endif

#ifndef ST7262_PANEL_CONFIG_DATA_B1
#define ST7262_PANEL_CONFIG_DATA_B1 21
#endif

#ifndef ST7262_PANEL_CONFIG_DATA_B2
#define ST7262_PANEL_CONFIG_DATA_B2 47
#endif

#ifndef ST7262_PANEL_CONFIG_DATA_B3
#define ST7262_PANEL_CONFIG_DATA_B3 48
#endif

#ifndef ST7262_PANEL_CONFIG_DATA_B4
#define ST7262_PANEL_CONFIG_DATA_B4 45
#endif

#ifndef ST7262_PANEL_CONFIG_DISP
#define ST7262_PANEL_CONFIG_DISP GPIO_NUM_NC
#endif

// GT911 Touch configuration
#ifndef GT911_I2C_CONFIG_SDA
#define GT911_I2C_CONFIG_SDA 19
#endif

#ifndef GT911_I2C_CONFIG_SCL
#define GT911_I2C_CONFIG_SCL 20
#endif

#ifndef GT911_TOUCH_CONFIG_RST
#define GT911_TOUCH_CONFIG_RST 38
#endif

#ifndef GT911_TOUCH_CONFIG_INT
#define GT911_TOUCH_CONFIG_INT 18
#endif

// >>> AUTO-GENERATED BUILD INFO BEGIN
#define FIRMWARE_BUILD_NUMBER "68084ab"
#define GIT_BRANCH "feature/binary-protocol-framing"
#define BUILD_TIMESTAMP_NUM "20250702_123805"
// <<< AUTO-GENERATED BUILD INFO END
#endif
