// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT connectionStatusPnl

lv_obj_t * ui_connectionStatusPnl_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_connectionStatusPnl;
    cui_connectionStatusPnl = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_connectionStatusPnl);
    lv_obj_set_width(cui_connectionStatusPnl, lv_pct(100));
    lv_obj_set_height(cui_connectionStatusPnl, LV_SIZE_CONTENT);    /// 100
    lv_obj_remove_flag(cui_connectionStatusPnl, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_lblWifi;
    cui_lblWifi = lv_label_create(cui_connectionStatusPnl);
    lv_obj_set_width(cui_lblWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_lblWifi, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(cui_lblWifi, "Wifi:");

    lv_obj_t * cui_lblWifiStatus;
    cui_lblWifiStatus = lv_label_create(cui_connectionStatusPnl);
    lv_obj_set_width(cui_lblWifiStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_lblWifiStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_lblWifiStatus, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(cui_lblWifiStatus, "-");

    lv_obj_t * cui_objWifiIndicator;
    cui_objWifiIndicator = lv_label_create(cui_connectionStatusPnl);
    lv_obj_set_width(cui_objWifiIndicator, 10);
    lv_obj_set_height(cui_objWifiIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_objWifiIndicator, -1);
    lv_obj_set_y(cui_objWifiIndicator, 0);
    lv_obj_set_align(cui_objWifiIndicator, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_objWifiIndicator, "");

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONNECTIONSTATUSPNL_NUM);
    children[UI_COMP_CONNECTIONSTATUSPNL_CONNECTIONSTATUSPNL] = cui_connectionStatusPnl;
    children[UI_COMP_CONNECTIONSTATUSPNL_LBLWIFI] = cui_lblWifi;
    children[UI_COMP_CONNECTIONSTATUSPNL_LBLWIFISTATUS] = cui_lblWifiStatus;
    children[UI_COMP_CONNECTIONSTATUSPNL_OBJWIFIINDICATOR] = cui_objWifiIndicator;
    lv_obj_add_event_cb(cui_connectionStatusPnl, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_connectionStatusPnl, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_connectionStatusPnl_create_hook(cui_connectionStatusPnl);
    return cui_connectionStatusPnl;
}

