// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT VolumeSlider

lv_obj_t * ui_VolumeSlider_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_VolumeSlider;
    cui_VolumeSlider = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_VolumeSlider);
    lv_obj_set_width(cui_VolumeSlider, 450);
    lv_obj_set_height(cui_VolumeSlider, 100);
    lv_obj_set_align(cui_VolumeSlider, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_VolumeSlider, LV_OBJ_FLAG_OVERFLOW_VISIBLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(cui_VolumeSlider, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_lblPrimaryVolumeSlider;
    cui_lblPrimaryVolumeSlider = lv_label_create(cui_VolumeSlider);
    lv_obj_set_width(cui_lblPrimaryVolumeSlider, 200);
    lv_obj_set_height(cui_lblPrimaryVolumeSlider, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_lblPrimaryVolumeSlider, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(cui_lblPrimaryVolumeSlider, LV_LABEL_LONG_CLIP);
    lv_label_set_text(cui_lblPrimaryVolumeSlider, "0%");
    lv_obj_set_style_text_align(cui_lblPrimaryVolumeSlider, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_lblPrimaryVolumeSlider, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_primaryVolumeSlider;
    cui_primaryVolumeSlider = lv_slider_create(cui_VolumeSlider);
    lv_slider_set_value(cui_primaryVolumeSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(cui_primaryVolumeSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            cui_primaryVolumeSlider, 0, LV_ANIM_OFF);
    lv_obj_set_height(cui_primaryVolumeSlider, 10);
    lv_obj_set_width(cui_primaryVolumeSlider, lv_pct(95));
    lv_obj_set_align(cui_primaryVolumeSlider, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(cui_primaryVolumeSlider,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(cui_primaryVolumeSlider,
                                                                                  lv_obj_get_style_pad_right(cui_primaryVolumeSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_VOLUMESLIDER_NUM);
    children[UI_COMP_VOLUMESLIDER_VOLUMESLIDER] = cui_VolumeSlider;
    children[UI_COMP_VOLUMESLIDER_LBLPRIMARYVOLUMESLIDER] = cui_lblPrimaryVolumeSlider;
    children[UI_COMP_VOLUMESLIDER_PRIMARYVOLUMESLIDER] = cui_primaryVolumeSlider;
    lv_obj_add_event_cb(cui_VolumeSlider, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_VolumeSlider, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_VolumeSlider_create_hook(cui_VolumeSlider);
    return cui_VolumeSlider;
}

