// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_COMP_VOLUMESLIDER_H
#define _UI_COMP_VOLUMESLIDER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT VolumeSlider
#define UI_COMP_VOLUMESLIDER_VOLUMESLIDER 0
#define UI_COMP_VOLUMESLIDER_LBLPRIMARYVOLUMESLIDER 1
#define UI_COMP_VOLUMESLIDER_PRIMARYVOLUMESLIDER 2
#define _UI_COMP_VOLUMESLIDER_NUM 3
lv_obj_t * ui_VolumeSlider_create(lv_obj_t * comp_parent);
void ui_event_comp_VolumeSlider_primaryVolumeSlider(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
