// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_COMP_CONNECTIONSTATUSPNL_H
#define _UI_COMP_CONNECTIONSTATUSPNL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT connectionStatusPnl
#define UI_COMP_CONNECTIONSTATUSPNL_CONNECTIONSTATUSPNL 0
#define UI_COMP_CONNECTIONSTATUSPNL_LBLWIFI 1
#define UI_COMP_CONNECTIONSTATUSPNL_LBLWIFISTATUS 2
#define UI_COMP_CONNECTIONSTATUSPNL_OBJWIFIINDICATOR 3
#define _UI_COMP_CONNECTIONSTATUSPNL_NUM 4
lv_obj_t * ui_connectionStatusPnl_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
