// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREENOTA_H
#define UI_SCREENOTA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenOTA
extern void ui_screenOTA_screen_init(void);
extern void ui_screenOTA_screen_destroy(void);
extern lv_obj_t * ui_screenOTA;
extern lv_obj_t * ui_pnlOTAUpdateProgress;
extern void ui_event_barOTAUpdateProgress(lv_event_t * e);
extern lv_obj_t * ui_barOTAUpdateProgress;
extern lv_obj_t * ui_lblOTAUpdateProgress;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

