// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_screenDebug;
lv_obj_t * ui_pnlContainerDebugLogs;
lv_obj_t * ui_lblDebugLogs;
lv_obj_t * ui_txtAreaDebugLog;
lv_obj_t * ui_btnBack;
lv_obj_t * ui_Label4;

// event funtions
void ui_event_btnBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenMain_screen_init);
    }
}

// build funtions

void ui_screenDebug_screen_init(void)
{
    ui_screenDebug = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screenDebug, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pnlContainerDebugLogs = lv_obj_create(ui_screenDebug);
    lv_obj_remove_style_all(ui_pnlContainerDebugLogs);
    lv_obj_set_width(ui_pnlContainerDebugLogs, lv_pct(80));
    lv_obj_set_height(ui_pnlContainerDebugLogs, lv_pct(80));
    lv_obj_set_align(ui_pnlContainerDebugLogs, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_pnlContainerDebugLogs, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_pnlContainerDebugLogs, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_pnlContainerDebugLogs, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblDebugLogs = lv_label_create(ui_pnlContainerDebugLogs);
    lv_obj_set_width(ui_lblDebugLogs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDebugLogs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblDebugLogs, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDebugLogs, "LOG");
    lv_obj_set_style_text_font(ui_lblDebugLogs, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtAreaDebugLog = lv_textarea_create(ui_pnlContainerDebugLogs);
    lv_obj_set_width(ui_txtAreaDebugLog, lv_pct(100));
    lv_obj_set_height(ui_txtAreaDebugLog, lv_pct(70));
    lv_obj_set_align(ui_txtAreaDebugLog, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_txtAreaDebugLog, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_txtAreaDebugLog, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_txtAreaDebugLog, "Your bugs will display here shortly...");

    ui_btnBack = lv_button_create(ui_screenDebug);
    lv_obj_set_width(ui_btnBack, 73);
    lv_obj_set_height(ui_btnBack, 40);
    lv_obj_set_x(ui_btnBack, 30);
    lv_obj_set_y(ui_btnBack, 30);
    lv_obj_add_flag(ui_btnBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_btnBack);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "BACK");

    lv_obj_add_event_cb(ui_btnBack, ui_event_btnBack, LV_EVENT_ALL, NULL);

}

void ui_screenDebug_screen_destroy(void)
{
    if(ui_screenDebug) lv_obj_del(ui_screenDebug);

    // NULL screen variables
    ui_screenDebug = NULL;
    ui_pnlContainerDebugLogs = NULL;
    ui_lblDebugLogs = NULL;
    ui_txtAreaDebugLog = NULL;
    ui_btnBack = NULL;
    ui_Label4 = NULL;

}
