// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREENDEBUG_H
#define UI_SCREENDEBUG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenDebug
extern void ui_screenDebug_screen_init(void);
extern void ui_screenDebug_screen_destroy(void);
extern lv_obj_t * ui_screenDebug;
extern lv_obj_t * ui_txtAreaDebugLog;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

