// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCRMAIN_H
#define UI_SCRMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrMain
extern void ui_scrMain_screen_init(void);
extern void ui_scrMain_screen_destroy(void);
extern lv_obj_t * ui_scrMain;
extern lv_obj_t * ui_pnlMain;
extern lv_obj_t * ui_lblMilliseconds;
extern lv_obj_t * ui_lblMillisecondsValue;
extern lv_obj_t * ui_lblCdr;
extern lv_obj_t * ui_lblCdrValue;
extern void ui_event_Rotate(lv_event_t * e);
extern lv_obj_t * ui_Rotate;
extern lv_obj_t * ui_Label1;
extern void ui_event_btnCount(lv_event_t * e);
extern lv_obj_t * ui_btnCount;
extern lv_obj_t * ui_lblButton;
extern lv_obj_t * ui_lblCount;
extern lv_obj_t * ui_lblCountValue;
extern lv_obj_t * ui_GradR;
extern lv_obj_t * ui_GradG;
extern lv_obj_t * ui_GradB;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

