// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_screenLogoViewer = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_screenMain_screen_init);
    }
}

void ui_event_Label3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_screenMain_screen_init);
    }
}

// build funtions

void ui_screenLogoViewer_screen_init(void)
{
    ui_screenLogoViewer = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screenLogoViewer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_button_create(ui_screenLogoViewer);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 20);
    lv_obj_set_y(ui_Button3, 0);
    lv_obj_set_align(ui_Button3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "BACK");

    lv_obj_add_event_cb(ui_Label3, ui_event_Label3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}

void ui_screenLogoViewer_screen_destroy(void)
{
    if(ui_screenLogoViewer) lv_obj_del(ui_screenLogoViewer);

    // NULL screen variables
    ui_screenLogoViewer = NULL;
    ui_Button3 = NULL;
    ui_Label3 = NULL;

}
