// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_btnAudio1;
lv_obj_t * ui_btnAudio2;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_btnAudio2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Slider2;
lv_obj_t * ui_btnAudio1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_pnlNetwork;
lv_obj_t * ui_lblWifi;
lv_obj_t * ui_lblWifiStatus;
lv_obj_t * ui_objWifiIndicator;
lv_obj_t * ui_lblSSID;
lv_obj_t * ui_lblSSIDValue;
lv_obj_t * ui_lblIP;
lv_obj_t * ui_lblIPValue;

// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_height(ui_Panel3, 100);
    lv_obj_set_width(ui_Panel3, lv_pct(100));
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_ROW_REVERSE);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Panel3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel3, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnAudio2 = lv_button_create(ui_Panel3);
    lv_obj_set_width(ui_btnAudio2, 100);
    lv_obj_set_height(ui_btnAudio2, 50);
    lv_obj_set_align(ui_btnAudio2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnAudio2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnAudio2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_btnAudio2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "text");

    ui_Slider2 = lv_slider_create(ui_Panel3);
    lv_slider_set_value(ui_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 356);
    lv_obj_set_height(ui_Slider2, 10);
    lv_obj_set_x(ui_Slider2, 408);
    lv_obj_set_y(ui_Slider2, -8);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider2,
                                                                                              lv_obj_get_style_pad_right(ui_Slider2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_btnAudio1 = lv_button_create(ui_Panel3);
    lv_obj_set_width(ui_btnAudio1, 100);
    lv_obj_set_height(ui_btnAudio1, 50);
    lv_obj_set_align(ui_btnAudio1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnAudio1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnAudio1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_btnAudio1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "text");

    ui_pnlNetwork = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_pnlNetwork, 200);
    lv_obj_set_height(ui_pnlNetwork, 100);
    lv_obj_remove_flag(ui_pnlNetwork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblWifi = lv_label_create(ui_pnlNetwork);
    lv_obj_set_width(ui_lblWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWifi, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_lblWifi, "Wifi:");

    ui_lblWifiStatus = lv_label_create(ui_pnlNetwork);
    lv_obj_set_width(ui_lblWifiStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWifiStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblWifiStatus, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_lblWifiStatus, "Wifi:");

    ui_objWifiIndicator = lv_label_create(ui_pnlNetwork);
    lv_obj_set_width(ui_objWifiIndicator, 10);
    lv_obj_set_height(ui_objWifiIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_objWifiIndicator, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_objWifiIndicator, "_");

    ui_lblSSID = lv_label_create(ui_pnlNetwork);
    lv_obj_set_width(ui_lblSSID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSSID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblSSID, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblSSID, "SSID:");

    ui_lblSSIDValue = lv_label_create(ui_pnlNetwork);
    lv_obj_set_width(ui_lblSSIDValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSSIDValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblSSIDValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSSIDValue, "SSID:");

    ui_lblIP = lv_label_create(ui_pnlNetwork);
    lv_obj_set_width(ui_lblIP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblIP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblIP, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_lblIP, "IP:");

    ui_lblIPValue = lv_label_create(ui_pnlNetwork);
    lv_obj_set_width(ui_lblIPValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblIPValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblIPValue, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lblIPValue, "IP:");

    ui_Panel3 = ui_Panel3;
    ui_btnAudio2 = ui_btnAudio2;
    ui_btnAudio1 = ui_btnAudio1;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Panel3 = NULL;
    ui_Panel3 = NULL;
    ui_btnAudio2 = NULL;
    ui_btnAudio2 = NULL;
    ui_Label3 = NULL;
    ui_Slider2 = NULL;
    ui_btnAudio1 = NULL;
    ui_btnAudio1 = NULL;
    ui_Label2 = NULL;
    ui_pnlNetwork = NULL;
    ui_lblWifi = NULL;
    ui_lblWifiStatus = NULL;
    ui_objWifiIndicator = NULL;
    ui_lblSSID = NULL;
    ui_lblSSIDValue = NULL;
    ui_lblIP = NULL;
    ui_lblIPValue = NULL;

}
