// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_screenFileExplorer = NULL;
// event funtions

// build funtions

void ui_screenFileExplorer_screen_init(void)
{
    ui_screenFileExplorer = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screenFileExplorer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_screenFileExplorer_screen_destroy(void)
{
    if(ui_screenFileExplorer) lv_obj_del(ui_screenFileExplorer);

    // NULL screen variables
    ui_screenFileExplorer = NULL;

}
