// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREENFILEEXPLORER_H
#define UI_SCREENFILEEXPLORER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenFileExplorer
extern void ui_screenFileExplorer_screen_init(void);
extern void ui_screenFileExplorer_screen_destroy(void);
extern lv_obj_t * ui_screenFileExplorer;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

