// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Dropdown2;
extern lv_obj_t * ui_pnlNetwork;
extern lv_obj_t * ui_wifiContainer;
extern lv_obj_t * ui_lblWifi;
extern lv_obj_t * ui_lblWifiStatus;
extern lv_obj_t * ui_objWifiIndicator;
extern lv_obj_t * ui_ssidContainer;
extern lv_obj_t * ui_lblSSID;
extern lv_obj_t * ui_lblSSIDValue;
extern lv_obj_t * ui_ipContainer;
extern lv_obj_t * ui_lblIP;
extern lv_obj_t * ui_lblIPValue;
extern lv_obj_t * ui_mqttContainer;
extern lv_obj_t * ui_lblMQTT;
extern lv_obj_t * ui_lblMQTTValue;
// CUSTOM VARIABLES
extern lv_obj_t * ui_Panel3;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

