// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_balanceVolumeSlider;
lv_obj_t * ui_lblBalanceVolumeSlider;
lv_obj_t * ui_singleVolumeSlider;
lv_obj_t * ui_lblSingleVolumeSlider;
lv_obj_t * ui_primaryVolumeSlider;
lv_obj_t * ui_lblPrimaryVolumeSlider;
lv_obj_t * ui_primaryContainer;
lv_obj_t * ui_screenMain = NULL;
lv_obj_t * ui_tabsModeSwitch = NULL;
lv_obj_t * ui_Master = NULL;
lv_obj_t * ui_pnlPrimaryAudioDevice = NULL;
lv_obj_t * ui_lblPrimaryAudioDeviceValue = NULL;
lv_obj_t * ui_primaryContainer = NULL;
lv_obj_t * ui_Single = NULL;
lv_obj_t * ui_pnlSingleSelectAudioDevice = NULL;
lv_obj_t * ui_selectAudioDevice = NULL;
lv_obj_t * ui_containerSingleVolumeSlider = NULL;
lv_obj_t * ui_Balance = NULL;
lv_obj_t * ui_pnlBalanceAudioDevices = NULL;
lv_obj_t * ui_selectAudioDevice2 = NULL;
lv_obj_t * ui_selectAudioDevice1 = NULL;
lv_obj_t * ui_containerBalanceVolumeSlider = NULL;
lv_obj_t * ui_statusView = NULL;
lv_obj_t * ui_containerBuildTime = NULL;
lv_obj_t * ui_lblBuildTime = NULL;
lv_obj_t * ui_lblBuildTimeValue = NULL;
lv_obj_t * ui_pnlSettings = NULL;
lv_obj_t * ui_lblSettingsHeader = NULL;
lv_obj_t * ui_actionBtns = NULL;
lv_obj_t * ui_btnGOTOSettings = NULL;
lv_obj_t * ui_btnLbl2 = NULL;
lv_obj_t * ui_btnRequestStatus = NULL;
lv_obj_t * ui_btnLbl3 = NULL;
lv_obj_t * ui_btnLogoDebug = NULL;
lv_obj_t * ui_btnLbl4 = NULL;
lv_obj_t * ui_lblFPS = NULL;
lv_obj_t * ui_img = NULL;
// event funtions
void ui_event_primaryContainer_primaryContainer_primaryVolumeSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_comp_get_child(ui_primaryContainer, UI_COMP_VOLUMESLIDER_LBLPRIMARYVOLUMESLIDER), target,
                                  "", "%");
    }
}

void ui_event_containerSingleVolumeSlider_containerSingleVolumeSlider_singleVolumeSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_comp_get_child(ui_containerSingleVolumeSlider,
                                                    UI_COMP_VOLUMESLIDER_LBLPRIMARYVOLUMESLIDER), target, "", "%");
    }
}

void ui_event_containerBalanceVolumeSlider_containerBalanceVolumeSlider_balanceVolumeSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_comp_get_child(ui_containerBalanceVolumeSlider,
                                                    UI_COMP_VOLUMESLIDER_LBLPRIMARYVOLUMESLIDER), target, "", "%");
    }
}

void ui_event_statusView(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        slideIntoFrame_Animation(ui_pnlSettings, 0);
    }
}

void ui_event_pnlSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        slideOutOfFrame_Animation(ui_pnlSettings, 0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        slideOutOfFrame_Animation(ui_pnlSettings, 0);
    }
}

void ui_event_btnGOTOSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        (e);
    }
}

// build funtions

void ui_screenMain_screen_init(void)
{
    ui_screenMain = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screenMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tabsModeSwitch = lv_tabview_create(ui_screenMain);
    lv_tabview_set_tab_bar_position(ui_tabsModeSwitch, LV_DIR_BOTTOM);
    lv_tabview_set_tab_bar_size(ui_tabsModeSwitch, 50);
    lv_obj_set_width(ui_tabsModeSwitch, lv_pct(100));
    lv_obj_set_height(ui_tabsModeSwitch, lv_pct(100));
    lv_obj_set_align(ui_tabsModeSwitch, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_tabsModeSwitch, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_border_width(lv_tabview_get_tab_bar(ui_tabsModeSwitch), 2,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(lv_tabview_get_tab_bar(ui_tabsModeSwitch), lv_color_hex(0xF90000),
                                  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_tabview_get_tab_bar(ui_tabsModeSwitch), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_tabview_get_tab_bar(ui_tabsModeSwitch), 2,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(lv_tabview_get_tab_bar(ui_tabsModeSwitch), LV_BORDER_SIDE_FULL,
                                 LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(lv_tabview_get_tab_bar(ui_tabsModeSwitch), lv_color_hex(0xE90000),
                                   LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(lv_tabview_get_tab_bar(ui_tabsModeSwitch), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(lv_tabview_get_tab_bar(ui_tabsModeSwitch), 3,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(lv_tabview_get_tab_bar(ui_tabsModeSwitch), 2,  LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_Master = lv_tabview_add_tab(ui_tabsModeSwitch, "Master");
    lv_obj_remove_flag(ui_Master, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pnlPrimaryAudioDevice = lv_obj_create(ui_Master);
    lv_obj_set_height(ui_pnlPrimaryAudioDevice, 50);
    lv_obj_set_width(ui_pnlPrimaryAudioDevice, lv_pct(100));
    lv_obj_set_align(ui_pnlPrimaryAudioDevice, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_pnlPrimaryAudioDevice, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblPrimaryAudioDeviceValue = lv_label_create(ui_pnlPrimaryAudioDevice);
    lv_obj_set_width(ui_lblPrimaryAudioDeviceValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPrimaryAudioDeviceValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblPrimaryAudioDeviceValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPrimaryAudioDeviceValue, "-");

    ui_primaryContainer = ui_VolumeSlider_create(ui_Master);
    lv_obj_set_x(ui_primaryContainer, 0);
    lv_obj_set_y(ui_primaryContainer, 0);
    lv_obj_add_flag(ui_primaryContainer, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags

    lv_obj_set_width(ui_comp_get_child(ui_primaryContainer, UI_COMP_VOLUMESLIDER_LBLPRIMARYVOLUMESLIDER), 200);
    lv_obj_set_height(ui_comp_get_child(ui_primaryContainer, UI_COMP_VOLUMESLIDER_LBLPRIMARYVOLUMESLIDER),
                      LV_SIZE_CONTENT);   /// 1
    lv_label_set_long_mode(ui_comp_get_child(ui_primaryContainer, UI_COMP_VOLUMESLIDER_LBLPRIMARYVOLUMESLIDER),
                           LV_LABEL_LONG_CLIP);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    ui_Single = lv_tabview_add_tab(ui_tabsModeSwitch, "Single");
    lv_obj_remove_flag(ui_Single, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags

    ui_pnlSingleSelectAudioDevice = lv_obj_create(ui_Single);
    lv_obj_set_height(ui_pnlSingleSelectAudioDevice, 50);
    lv_obj_set_width(ui_pnlSingleSelectAudioDevice, lv_pct(100));
    lv_obj_set_align(ui_pnlSingleSelectAudioDevice, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_pnlSingleSelectAudioDevice, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_selectAudioDevice = lv_dropdown_create(ui_pnlSingleSelectAudioDevice);
    lv_dropdown_set_options(ui_selectAudioDevice, "None 1\nNone 2\nNone 3");
    lv_obj_set_width(ui_selectAudioDevice, lv_pct(50));
    lv_obj_set_height(ui_selectAudioDevice, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_selectAudioDevice, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_selectAudioDevice, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_containerSingleVolumeSlider = ui_VolumeSlider_create(ui_Single);
    lv_obj_set_x(ui_containerSingleVolumeSlider, 0);
    lv_obj_set_y(ui_containerSingleVolumeSlider, 0);

    lv_obj_set_width(ui_comp_get_child(ui_containerSingleVolumeSlider, UI_COMP_VOLUMESLIDER_LBLPRIMARYVOLUMESLIDER), 200);
    lv_obj_set_height(ui_comp_get_child(ui_containerSingleVolumeSlider, UI_COMP_VOLUMESLIDER_LBLPRIMARYVOLUMESLIDER),
                      LV_SIZE_CONTENT);   /// 1
    lv_label_set_long_mode(ui_comp_get_child(ui_containerSingleVolumeSlider, UI_COMP_VOLUMESLIDER_LBLPRIMARYVOLUMESLIDER),
                           LV_LABEL_LONG_CLIP);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    ui_Balance = lv_tabview_add_tab(ui_tabsModeSwitch, "Balance");
    lv_obj_remove_flag(ui_Balance, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pnlBalanceAudioDevices = lv_obj_create(ui_Balance);
    lv_obj_set_height(ui_pnlBalanceAudioDevices, 50);
    lv_obj_set_width(ui_pnlBalanceAudioDevices, lv_pct(100));
    lv_obj_set_align(ui_pnlBalanceAudioDevices, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_pnlBalanceAudioDevices, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_pnlBalanceAudioDevices, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_pnlBalanceAudioDevices, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_selectAudioDevice2 = lv_dropdown_create(ui_pnlBalanceAudioDevices);
    lv_dropdown_set_options(ui_selectAudioDevice2, "None");
    lv_obj_set_width(ui_selectAudioDevice2, lv_pct(49));
    lv_obj_set_height(ui_selectAudioDevice2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_selectAudioDevice2, 0);
    lv_obj_set_y(ui_selectAudioDevice2, -1);
    lv_obj_set_align(ui_selectAudioDevice2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_selectAudioDevice2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_selectAudioDevice1 = lv_dropdown_create(ui_pnlBalanceAudioDevices);
    lv_dropdown_set_options(ui_selectAudioDevice1, "None");
    lv_obj_set_width(ui_selectAudioDevice1, lv_pct(49));
    lv_obj_set_height(ui_selectAudioDevice1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_selectAudioDevice1, 0);
    lv_obj_set_y(ui_selectAudioDevice1, -1);
    lv_obj_set_align(ui_selectAudioDevice1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_selectAudioDevice1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_containerBalanceVolumeSlider = ui_VolumeSlider_create(ui_Balance);
    lv_obj_set_x(ui_containerBalanceVolumeSlider, 0);
    lv_obj_set_y(ui_containerBalanceVolumeSlider, 0);

    lv_obj_set_width(ui_comp_get_child(ui_containerBalanceVolumeSlider, UI_COMP_VOLUMESLIDER_LBLPRIMARYVOLUMESLIDER), 200);
    lv_obj_set_height(ui_comp_get_child(ui_containerBalanceVolumeSlider, UI_COMP_VOLUMESLIDER_LBLPRIMARYVOLUMESLIDER),
                      LV_SIZE_CONTENT);   /// 1
    lv_label_set_long_mode(ui_comp_get_child(ui_containerBalanceVolumeSlider, UI_COMP_VOLUMESLIDER_LBLPRIMARYVOLUMESLIDER),
                           LV_LABEL_LONG_CLIP);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    ui_statusView = lv_obj_create(ui_tabsModeSwitch);
    lv_obj_remove_style_all(ui_statusView);
    lv_obj_set_height(ui_statusView, 30);
    lv_obj_set_width(ui_statusView, lv_pct(100));
    lv_obj_set_align(ui_statusView, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_statusView, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_statusView, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_add_flag(ui_statusView, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_statusView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_statusView, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_statusView, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_statusView, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_statusView, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_containerBuildTime = lv_obj_create(ui_statusView);
    lv_obj_remove_style_all(ui_containerBuildTime);
    lv_obj_set_height(ui_containerBuildTime, 50);
    lv_obj_set_width(ui_containerBuildTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_containerBuildTime, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_containerBuildTime, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_containerBuildTime, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_containerBuildTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblBuildTime = lv_label_create(ui_containerBuildTime);
    lv_obj_set_width(ui_lblBuildTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBuildTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblBuildTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBuildTime, "Build: ");

    ui_lblBuildTimeValue = lv_label_create(ui_containerBuildTime);
    lv_obj_set_width(ui_lblBuildTimeValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBuildTimeValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblBuildTimeValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBuildTimeValue, "9:41 PM    12/12");

    ui_pnlSettings = lv_obj_create(ui_screenMain);
    lv_obj_set_width(ui_pnlSettings, 400);
    lv_obj_set_height(ui_pnlSettings, 200);
    lv_obj_set_x(ui_pnlSettings, 0);
    lv_obj_set_y(ui_pnlSettings, -200);
    lv_obj_set_align(ui_pnlSettings, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_pnlSettings, LV_OBJ_FLAG_IGNORE_LAYOUT | LV_OBJ_FLAG_FLOATING | LV_OBJ_FLAG_OVERFLOW_VISIBLE |
                    LV_OBJ_FLAG_EVENT_BUBBLE);    /// Flags
    lv_obj_remove_flag(ui_pnlSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_pnlSettings, lv_color_hex(0x2765C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlSettings, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pnlSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pnlSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSettingsHeader = lv_label_create(ui_pnlSettings);
    lv_obj_set_width(ui_lblSettingsHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSettingsHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblSettingsHeader, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblSettingsHeader, "SETTINGS");
    lv_obj_set_style_text_font(ui_lblSettingsHeader, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_actionBtns = lv_obj_create(ui_pnlSettings);
    lv_obj_remove_style_all(ui_actionBtns);
    lv_obj_set_width(ui_actionBtns, lv_pct(50));
    lv_obj_set_height(ui_actionBtns, lv_pct(80));
    lv_obj_set_align(ui_actionBtns, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_actionBtns, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_actionBtns, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_remove_flag(ui_actionBtns, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnGOTOSettings = lv_button_create(ui_actionBtns);
    lv_obj_set_width(ui_btnGOTOSettings, lv_pct(100));
    lv_obj_set_height(ui_btnGOTOSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_btnGOTOSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnGOTOSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnGOTOSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnLbl2 = lv_label_create(ui_btnGOTOSettings);
    lv_obj_set_width(ui_btnLbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_btnLbl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_btnLbl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btnLbl2, "System Overview");

    ui_btnRequestStatus = lv_button_create(ui_actionBtns);
    lv_obj_set_width(ui_btnRequestStatus, lv_pct(100));
    lv_obj_set_height(ui_btnRequestStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_btnRequestStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnRequestStatus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnRequestStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnLbl3 = lv_label_create(ui_btnRequestStatus);
    lv_obj_set_width(ui_btnLbl3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_btnLbl3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_btnLbl3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btnLbl3, "Request Status");

    ui_btnLogoDebug = lv_button_create(ui_actionBtns);
    lv_obj_set_width(ui_btnLogoDebug, lv_pct(100));
    lv_obj_set_height(ui_btnLogoDebug, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_btnLogoDebug, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnLogoDebug, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnLogoDebug, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnLbl4 = lv_label_create(ui_btnLogoDebug);
    lv_obj_set_width(ui_btnLbl4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_btnLbl4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_btnLbl4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btnLbl4, "Logo Debug");

    ui_lblFPS = lv_label_create(ui_screenMain);
    lv_obj_set_width(ui_lblFPS, 100);
    lv_obj_set_height(ui_lblFPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblFPS, -78);
    lv_obj_set_y(ui_lblFPS, 30);
    lv_obj_set_align(ui_lblFPS, LV_ALIGN_TOP_RIGHT);
    lv_label_set_long_mode(ui_lblFPS, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_lblFPS, "FPS: 1000");

    ui_img = lv_image_create(ui_screenMain);
    lv_obj_set_width(ui_img, 100);
    lv_obj_set_height(ui_img, 100);
    lv_obj_set_x(ui_img, 255);
    lv_obj_set_y(ui_img, -67);
    lv_obj_set_align(ui_img, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_FLOATING |
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);    /// Flags
    lv_obj_remove_flag(ui_img, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_img, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_comp_get_child(ui_primaryContainer, UI_COMP_VOLUMESLIDER_PRIMARYVOLUMESLIDER),
                        ui_event_primaryContainer_primaryContainer_primaryVolumeSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_containerSingleVolumeSlider, UI_COMP_VOLUMESLIDER_PRIMARYVOLUMESLIDER),
                        ui_event_containerSingleVolumeSlider_containerSingleVolumeSlider_singleVolumeSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_containerBalanceVolumeSlider, UI_COMP_VOLUMESLIDER_PRIMARYVOLUMESLIDER),
                        ui_event_containerBalanceVolumeSlider_containerBalanceVolumeSlider_balanceVolumeSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_statusView, ui_event_statusView, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnGOTOSettings, ui_event_btnGOTOSettings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pnlSettings, ui_event_pnlSettings, LV_EVENT_ALL, NULL);
    ui_primaryContainer = ui_primaryContainer;
    ui_lblPrimaryVolumeSlider = ui_comp_get_child(ui_primaryContainer, UI_COMP_VOLUMESLIDER_LBLPRIMARYVOLUMESLIDER);
    ui_primaryVolumeSlider = ui_comp_get_child(ui_primaryContainer, UI_COMP_VOLUMESLIDER_PRIMARYVOLUMESLIDER);
    ui_lblSingleVolumeSlider = ui_comp_get_child(ui_containerSingleVolumeSlider,
                                                 UI_COMP_VOLUMESLIDER_LBLPRIMARYVOLUMESLIDER);
    ui_singleVolumeSlider = ui_comp_get_child(ui_containerSingleVolumeSlider, UI_COMP_VOLUMESLIDER_PRIMARYVOLUMESLIDER);
    ui_lblBalanceVolumeSlider = ui_comp_get_child(ui_containerBalanceVolumeSlider,
                                                  UI_COMP_VOLUMESLIDER_LBLPRIMARYVOLUMESLIDER);
    ui_balanceVolumeSlider = ui_comp_get_child(ui_containerBalanceVolumeSlider, UI_COMP_VOLUMESLIDER_PRIMARYVOLUMESLIDER);

}

void ui_screenMain_screen_destroy(void)
{
    if(ui_screenMain) lv_obj_del(ui_screenMain);

    // NULL screen variables
    ui_screenMain = NULL;
    ui_tabsModeSwitch = NULL;
    ui_Master = NULL;
    ui_pnlPrimaryAudioDevice = NULL;
    ui_lblPrimaryAudioDeviceValue = NULL;
    ui_primaryContainer = NULL;
    ui_primaryContainer = NULL;
    ui_lblPrimaryVolumeSlider = NULL;
    ui_primaryVolumeSlider = NULL;
    ui_Single = NULL;
    ui_pnlSingleSelectAudioDevice = NULL;
    ui_selectAudioDevice = NULL;
    ui_containerSingleVolumeSlider = NULL;
    ui_lblSingleVolumeSlider = NULL;
    ui_singleVolumeSlider = NULL;
    ui_Balance = NULL;
    ui_pnlBalanceAudioDevices = NULL;
    ui_selectAudioDevice2 = NULL;
    ui_selectAudioDevice1 = NULL;
    ui_containerBalanceVolumeSlider = NULL;
    ui_lblBalanceVolumeSlider = NULL;
    ui_balanceVolumeSlider = NULL;
    ui_statusView = NULL;
    ui_containerBuildTime = NULL;
    ui_lblBuildTime = NULL;
    ui_lblBuildTimeValue = NULL;
    ui_pnlSettings = NULL;
    ui_lblSettingsHeader = NULL;
    ui_actionBtns = NULL;
    ui_btnGOTOSettings = NULL;
    ui_btnLbl2 = NULL;
    ui_btnRequestStatus = NULL;
    ui_btnLbl3 = NULL;
    ui_btnLogoDebug = NULL;
    ui_btnLbl4 = NULL;
    ui_lblFPS = NULL;
    ui_img = NULL;

}
