// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREENMAIN_H
#define UI_SCREENMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenMain
extern void ui_screenMain_screen_init(void);
extern void ui_screenMain_screen_destroy(void);
extern lv_obj_t * ui_screenMain;
extern lv_obj_t * ui_tabsModeSwitch;
extern lv_obj_t * ui_Master;
extern lv_obj_t * ui_pnlPrimaryAudioDevice;
extern lv_obj_t * ui_lblPrimaryAudioDeviceValue;
extern lv_obj_t * ui_primaryVolumeSlider;
extern void ui_event_primaryVolumeSlider_primaryVolumeSlider(lv_event_t * e);
extern lv_obj_t * ui_Single;
extern lv_obj_t * ui_pnlSingleSelectAudioDevice;
extern lv_obj_t * ui_selectAudioDevice;
extern lv_obj_t * ui_containerSingleVolumeSlider;
extern void ui_event_containerSingleVolumeSlider_containerSingleVolumeSlider_singleVolumeSlider(lv_event_t * e);
extern lv_obj_t * ui_Balance;
extern lv_obj_t * ui_pnlBalanceAudioDevices;
extern lv_obj_t * ui_selectAudioDevice2;
extern lv_obj_t * ui_selectAudioDevice1;
extern lv_obj_t * ui_containerBalanceVolumeSlider;
extern void ui_event_containerBalanceVolumeSlider_containerBalanceVolumeSlider_balanceVolumeSlider(lv_event_t * e);
extern void ui_event_statusView(lv_event_t * e);
extern lv_obj_t * ui_statusView;
extern lv_obj_t * ui_containerBuildTime;
extern lv_obj_t * ui_lblBuildTime;
extern lv_obj_t * ui_lblBuildTimeValue;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label3;
extern void ui_event_pnlSettings(lv_event_t * e);
extern lv_obj_t * ui_pnlSettings;
extern lv_obj_t * ui_lblSettingsHeader;
extern lv_obj_t * ui_actionBtns;
extern void ui_event_btnGOTOLog(lv_event_t * e);
extern lv_obj_t * ui_btnGOTOLog;
extern lv_obj_t * ui_btnLbl1;
extern void ui_event_btnGOTOSettings(lv_event_t * e);
extern lv_obj_t * ui_btnGOTOSettings;
extern lv_obj_t * ui_btnLbl2;
extern lv_obj_t * ui_btnRequestStatus;
extern lv_obj_t * ui_btnLbl3;
extern lv_obj_t * ui_pnlNetwork;
extern lv_obj_t * ui_wifiContainer;
extern lv_obj_t * ui_lblWifi;
extern lv_obj_t * ui_lblWifiStatus;
extern lv_obj_t * ui_objWifiIndicator;
extern lv_obj_t * ui_ssidContainer;
extern lv_obj_t * ui_lblSSID;
extern lv_obj_t * ui_lblSSIDValue;
extern lv_obj_t * ui_ipContainer;
extern lv_obj_t * ui_lblIP;
extern lv_obj_t * ui_lblIPValue;
extern lv_obj_t * ui_sdContainer;
extern lv_obj_t * ui_lblSD;
extern lv_obj_t * ui_objSDIndicator;
extern lv_obj_t * ui_lblSDStatus;
extern lv_obj_t * ui_mqttContainer;
extern lv_obj_t * ui_lblMQTT;
extern lv_obj_t * ui_objMQTTIndicator;
extern lv_obj_t * ui_lblMQTTValue;
extern lv_obj_t * ui_lblFPS;
extern lv_obj_t * ui_img;
// CUSTOM VARIABLES
extern lv_obj_t * ui_lblPrimaryVolumeSlider;
extern lv_obj_t * ui_lblSingleVolumeSlider;
extern lv_obj_t * ui_singleVolumeSlider;
extern lv_obj_t * ui_lblBalanceVolumeSlider;
extern lv_obj_t * ui_balanceVolumeSlider;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

