// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_btnAudio2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_btnAudio1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_pnlNetwork;
extern lv_obj_t * ui_lblWifi;
extern lv_obj_t * ui_lblWifiStatus;
extern lv_obj_t * ui_objWifiIndicator;
extern lv_obj_t * ui_lblSSID;
extern lv_obj_t * ui_lblSSIDValue;
extern lv_obj_t * ui_lblIP;
extern lv_obj_t * ui_lblIPValue;
// CUSTOM VARIABLES
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_btnAudio2;
extern lv_obj_t * ui_btnAudio1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

