// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREENMAIN_H
#define UI_SCREENMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenMain
extern void ui_screenMain_screen_init(void);
extern void ui_screenMain_screen_destroy(void);
extern lv_obj_t * ui_screenMain;
extern lv_obj_t * ui_TabView3;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_selectAudioDevice;
extern lv_obj_t * ui_Balance;
extern lv_obj_t * ui_selectAudioDevice1;
extern lv_obj_t * ui_selectAudioDevice2;
extern lv_obj_t * ui_pnlNetwork;
extern lv_obj_t * ui_wifiContainer;
extern lv_obj_t * ui_lblWifi;
extern lv_obj_t * ui_lblWifiStatus;
extern lv_obj_t * ui_objWifiIndicator;
extern lv_obj_t * ui_ssidContainer;
extern lv_obj_t * ui_lblSSID;
extern lv_obj_t * ui_lblSSIDValue;
extern lv_obj_t * ui_ipContainer;
extern lv_obj_t * ui_lblIP;
extern lv_obj_t * ui_lblIPValue;
extern lv_obj_t * ui_mqttContainer;
extern lv_obj_t * ui_lblMQTT;
extern lv_obj_t * ui_objMQTTIndicator;
extern lv_obj_t * ui_lblMQTTValue;
extern lv_obj_t * ui_pnlVolumeSlider;
extern lv_obj_t * ui_volumeSliderLbl;
extern lv_obj_t * ui_volumeSlider;
extern lv_obj_t * ui_btnRequestData;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_lblFPS;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

