// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_screenDebug;
lv_obj_t * ui_txtAreaDebugLog;

// event funtions

// build funtions

void ui_screenDebug_screen_init(void)
{
    ui_screenDebug = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screenDebug, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_txtAreaDebugLog = lv_textarea_create(ui_screenDebug);
    lv_obj_set_width(ui_txtAreaDebugLog, lv_pct(80));
    lv_obj_set_height(ui_txtAreaDebugLog, lv_pct(80));
    lv_obj_set_align(ui_txtAreaDebugLog, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_txtAreaDebugLog, "Placeholder...");

}

void ui_screenDebug_screen_destroy(void)
{
    if(ui_screenDebug) lv_obj_del(ui_screenDebug);

    // NULL screen variables
    ui_screenDebug = NULL;
    ui_txtAreaDebugLog = NULL;

}
