// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_screenOTA;
lv_obj_t * ui_pnlOTAUpdateProgress;
lv_obj_t * ui_barOTAUpdateProgress;
lv_obj_t * ui_lblOTAUpdateProgress;
lv_obj_t * ui_Label2;

// event funtions
void ui_event_barOTAUpdateProgress(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_lblOTAUpdateProgress, target, "", "%");
    }
}

// build funtions

void ui_screenOTA_screen_init(void)
{
    ui_screenOTA = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screenOTA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pnlOTAUpdateProgress = lv_obj_create(ui_screenOTA);
    lv_obj_set_width(ui_pnlOTAUpdateProgress, 347);
    lv_obj_set_height(ui_pnlOTAUpdateProgress, 93);
    lv_obj_set_align(ui_pnlOTAUpdateProgress, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_pnlOTAUpdateProgress, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_pnlOTAUpdateProgress, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlOTAUpdateProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barOTAUpdateProgress = lv_bar_create(ui_pnlOTAUpdateProgress);
    lv_bar_set_value(ui_barOTAUpdateProgress, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barOTAUpdateProgress, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_barOTAUpdateProgress, 10);
    lv_obj_set_width(ui_barOTAUpdateProgress, lv_pct(80));
    lv_obj_set_x(ui_barOTAUpdateProgress, 0);
    lv_obj_set_y(ui_barOTAUpdateProgress, 11);
    lv_obj_set_align(ui_barOTAUpdateProgress, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_barOTAUpdateProgress,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_barOTAUpdateProgress,
                                                                                  lv_obj_get_style_pad_right(ui_barOTAUpdateProgress, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_lblOTAUpdateProgress = lv_label_create(ui_pnlOTAUpdateProgress);
    lv_obj_set_width(ui_lblOTAUpdateProgress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblOTAUpdateProgress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblOTAUpdateProgress, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblOTAUpdateProgress, "text");

    ui_Label2 = lv_label_create(ui_screenOTA);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 31);
    lv_obj_set_align(ui_Label2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label2, "UPDATING");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_barOTAUpdateProgress, ui_event_barOTAUpdateProgress, LV_EVENT_ALL, NULL);

}

void ui_screenOTA_screen_destroy(void)
{
    if(ui_screenOTA) lv_obj_del(ui_screenOTA);

    // NULL screen variables
    ui_screenOTA = NULL;
    ui_pnlOTAUpdateProgress = NULL;
    ui_barOTAUpdateProgress = NULL;
    ui_lblOTAUpdateProgress = NULL;
    ui_Label2 = NULL;

}
