// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_screenMain;
lv_obj_t * ui_TabView3;
lv_obj_t * ui_TabPage2;
lv_obj_t * ui_selectAudioDevice;
lv_obj_t * ui_Balance;
lv_obj_t * ui_selectAudioDevice1;
lv_obj_t * ui_selectAudioDevice2;
lv_obj_t * ui_pnlNetwork;
lv_obj_t * ui_wifiContainer;
lv_obj_t * ui_lblWifi;
lv_obj_t * ui_lblWifiStatus;
lv_obj_t * ui_objWifiIndicator;
lv_obj_t * ui_ssidContainer;
lv_obj_t * ui_lblSSID;
lv_obj_t * ui_lblSSIDValue;
lv_obj_t * ui_ipContainer;
lv_obj_t * ui_lblIP;
lv_obj_t * ui_lblIPValue;
lv_obj_t * ui_mqttContainer;
lv_obj_t * ui_lblMQTT;
lv_obj_t * ui_objMQTTIndicator;
lv_obj_t * ui_lblMQTTValue;
lv_obj_t * ui_Container3;
lv_obj_t * ui_btnRequestData;
lv_obj_t * ui_Label5;
lv_obj_t * ui_btnGOTOLog;
lv_obj_t * ui_Label1;
lv_obj_t * ui_lblFPS;
lv_obj_t * ui_containerVolumeSlider;
lv_obj_t * ui_volumeSliderLbl;
lv_obj_t * ui_volumeSlider;

// event funtions
void ui_event_btnGOTOLog(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenDebug, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenDebug_screen_init);
    }
}

// build funtions

void ui_screenMain_screen_init(void)
{
    ui_screenMain = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screenMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView3 = lv_tabview_create(ui_screenMain);
    lv_tabview_set_tab_bar_size(ui_TabView3, 50);
    lv_obj_set_width(ui_TabView3, lv_pct(100));
    lv_obj_set_height(ui_TabView3, lv_pct(100));
    lv_obj_set_align(ui_TabView3, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_TabView3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView3, "Primary");
    lv_obj_set_flex_flow(ui_TabPage2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TabPage2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);

    ui_selectAudioDevice = lv_dropdown_create(ui_TabPage2);
    lv_dropdown_set_options(ui_selectAudioDevice, "None");
    lv_obj_set_width(ui_selectAudioDevice, lv_pct(50));
    lv_obj_set_height(ui_selectAudioDevice, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_selectAudioDevice, -1);
    lv_obj_set_y(ui_selectAudioDevice, -1);
    lv_obj_set_align(ui_selectAudioDevice, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_selectAudioDevice, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Balance = lv_tabview_add_tab(ui_TabView3, "Balance");
    lv_obj_set_flex_flow(ui_Balance, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Balance, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);

    ui_selectAudioDevice1 = lv_dropdown_create(ui_Balance);
    lv_dropdown_set_options(ui_selectAudioDevice1, "None");
    lv_obj_set_width(ui_selectAudioDevice1, lv_pct(49));
    lv_obj_set_height(ui_selectAudioDevice1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_selectAudioDevice1, 0);
    lv_obj_set_y(ui_selectAudioDevice1, -1);
    lv_obj_set_align(ui_selectAudioDevice1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_selectAudioDevice1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_selectAudioDevice2 = lv_dropdown_create(ui_Balance);
    lv_dropdown_set_options(ui_selectAudioDevice2, "None");
    lv_obj_set_width(ui_selectAudioDevice2, lv_pct(49));
    lv_obj_set_height(ui_selectAudioDevice2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_selectAudioDevice2, 0);
    lv_obj_set_y(ui_selectAudioDevice2, -1);
    lv_obj_set_align(ui_selectAudioDevice2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_selectAudioDevice2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_pnlNetwork = lv_obj_create(ui_screenMain);
    lv_obj_set_width(ui_pnlNetwork, 200);
    lv_obj_set_height(ui_pnlNetwork, 200);
    lv_obj_set_x(ui_pnlNetwork, 7);
    lv_obj_set_y(ui_pnlNetwork, -107);
    lv_obj_set_align(ui_pnlNetwork, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_pnlNetwork, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_pnlNetwork, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_pnlNetwork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiContainer = lv_obj_create(ui_pnlNetwork);
    lv_obj_remove_style_all(ui_wifiContainer);
    lv_obj_set_width(ui_wifiContainer, lv_pct(100));
    lv_obj_set_height(ui_wifiContainer, LV_SIZE_CONTENT);    /// 100
    lv_obj_remove_flag(ui_wifiContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblWifi = lv_label_create(ui_wifiContainer);
    lv_obj_set_width(ui_lblWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWifi, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_lblWifi, "Wifi:");

    ui_lblWifiStatus = lv_label_create(ui_wifiContainer);
    lv_obj_set_width(ui_lblWifiStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWifiStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblWifiStatus, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_lblWifiStatus, "-");

    ui_objWifiIndicator = lv_label_create(ui_wifiContainer);
    lv_obj_set_width(ui_objWifiIndicator, 10);
    lv_obj_set_height(ui_objWifiIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_objWifiIndicator, -1);
    lv_obj_set_y(ui_objWifiIndicator, 0);
    lv_obj_set_align(ui_objWifiIndicator, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_objWifiIndicator, "");

    ui_ssidContainer = lv_obj_create(ui_pnlNetwork);
    lv_obj_remove_style_all(ui_ssidContainer);
    lv_obj_set_width(ui_ssidContainer, lv_pct(100));
    lv_obj_set_height(ui_ssidContainer, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_ssidContainer, -257);
    lv_obj_set_y(ui_ssidContainer, -111);
    lv_obj_remove_flag(ui_ssidContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblSSID = lv_label_create(ui_ssidContainer);
    lv_obj_set_width(ui_lblSSID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSSID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblSSID, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblSSID, "SSID:");

    ui_lblSSIDValue = lv_label_create(ui_ssidContainer);
    lv_obj_set_width(ui_lblSSIDValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSSIDValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblSSIDValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lblSSIDValue, "-");

    ui_ipContainer = lv_obj_create(ui_pnlNetwork);
    lv_obj_remove_style_all(ui_ipContainer);
    lv_obj_set_width(ui_ipContainer, lv_pct(100));
    lv_obj_set_height(ui_ipContainer, LV_SIZE_CONTENT);    /// 1
    lv_obj_remove_flag(ui_ipContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblIP = lv_label_create(ui_ipContainer);
    lv_obj_set_width(ui_lblIP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblIP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblIP, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_lblIP, "IP:");

    ui_lblIPValue = lv_label_create(ui_ipContainer);
    lv_obj_set_width(ui_lblIPValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblIPValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblIPValue, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_lblIPValue, "-");

    ui_mqttContainer = lv_obj_create(ui_pnlNetwork);
    lv_obj_remove_style_all(ui_mqttContainer);
    lv_obj_set_width(ui_mqttContainer, lv_pct(100));
    lv_obj_set_height(ui_mqttContainer, LV_SIZE_CONTENT);    /// 1
    lv_obj_remove_flag(ui_mqttContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblMQTT = lv_label_create(ui_mqttContainer);
    lv_obj_set_width(ui_lblMQTT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMQTT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblMQTT, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_lblMQTT, "MQTT:");

    ui_objMQTTIndicator = lv_label_create(ui_mqttContainer);
    lv_obj_set_width(ui_objMQTTIndicator, 10);
    lv_obj_set_height(ui_objMQTTIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_objMQTTIndicator, -1);
    lv_obj_set_y(ui_objMQTTIndicator, 0);
    lv_obj_set_align(ui_objMQTTIndicator, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_objMQTTIndicator, "");

    ui_lblMQTTValue = lv_label_create(ui_mqttContainer);
    lv_obj_set_width(ui_lblMQTTValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMQTTValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblMQTTValue, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_lblMQTTValue, "-");

    ui_Container3 = lv_obj_create(ui_pnlNetwork);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 163);
    lv_obj_set_height(ui_Container3, 50);
    lv_obj_set_x(ui_Container3, -86);
    lv_obj_set_y(ui_Container3, -12);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnRequestData = lv_button_create(ui_Container3);
    lv_obj_set_width(ui_btnRequestData, 74);
    lv_obj_set_height(ui_btnRequestData, 27);
    lv_obj_set_align(ui_btnRequestData, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnRequestData, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnRequestData, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_btnRequestData);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Refresh");

    ui_btnGOTOLog = lv_button_create(ui_Container3);
    lv_obj_set_width(ui_btnGOTOLog, 74);
    lv_obj_set_height(ui_btnGOTOLog, 24);
    lv_obj_set_align(ui_btnGOTOLog, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnGOTOLog, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnGOTOLog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_btnGOTOLog);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "LOG");

    ui_lblFPS = lv_label_create(ui_screenMain);
    lv_obj_set_width(ui_lblFPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblFPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblFPS, 347);
    lv_obj_set_y(ui_lblFPS, -125);
    lv_obj_set_align(ui_lblFPS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblFPS, "FPS: 1000");

    ui_containerVolumeSlider = lv_obj_create(ui_screenMain);
    lv_obj_remove_style_all(ui_containerVolumeSlider);
    lv_obj_set_width(ui_containerVolumeSlider, lv_pct(80));
    lv_obj_set_height(ui_containerVolumeSlider, lv_pct(80));
    lv_obj_set_align(ui_containerVolumeSlider, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_containerVolumeSlider, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_volumeSliderLbl = lv_label_create(ui_containerVolumeSlider);
    lv_obj_set_width(ui_volumeSliderLbl, lv_pct(100));
    lv_obj_set_height(ui_volumeSliderLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_volumeSliderLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_volumeSliderLbl, "0%");
    lv_obj_set_style_text_align(ui_volumeSliderLbl, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_volumeSliderLbl, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumeSlider = lv_arc_create(ui_containerVolumeSlider);
    lv_obj_set_width(ui_volumeSlider, lv_pct(40));
    lv_obj_set_height(ui_volumeSlider, lv_pct(80));
    lv_obj_set_align(ui_volumeSlider, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_volumeSlider, 0);
    lv_obj_set_style_arc_color(ui_volumeSlider, lv_color_hex(0xD9D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_volumeSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_volumeSlider, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_volumeSlider, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnGOTOLog, ui_event_btnGOTOLog, LV_EVENT_ALL, NULL);

}

void ui_screenMain_screen_destroy(void)
{
    if(ui_screenMain) lv_obj_del(ui_screenMain);

    // NULL screen variables
    ui_screenMain = NULL;
    ui_TabView3 = NULL;
    ui_TabPage2 = NULL;
    ui_selectAudioDevice = NULL;
    ui_Balance = NULL;
    ui_selectAudioDevice1 = NULL;
    ui_selectAudioDevice2 = NULL;
    ui_pnlNetwork = NULL;
    ui_wifiContainer = NULL;
    ui_lblWifi = NULL;
    ui_lblWifiStatus = NULL;
    ui_objWifiIndicator = NULL;
    ui_ssidContainer = NULL;
    ui_lblSSID = NULL;
    ui_lblSSIDValue = NULL;
    ui_ipContainer = NULL;
    ui_lblIP = NULL;
    ui_lblIPValue = NULL;
    ui_mqttContainer = NULL;
    ui_lblMQTT = NULL;
    ui_objMQTTIndicator = NULL;
    ui_lblMQTTValue = NULL;
    ui_Container3 = NULL;
    ui_btnRequestData = NULL;
    ui_Label5 = NULL;
    ui_btnGOTOLog = NULL;
    ui_Label1 = NULL;
    ui_lblFPS = NULL;
    ui_containerVolumeSlider = NULL;
    ui_volumeSliderLbl = NULL;
    ui_volumeSlider = NULL;

}
