// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_screenStateOverview = NULL;
// event funtions

// build funtions

void ui_screenStateOverview_screen_init(void)
{
    ui_screenStateOverview = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screenStateOverview, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_screenStateOverview_screen_destroy(void)
{
    if(ui_screenStateOverview) lv_obj_del(ui_screenStateOverview);

    // NULL screen variables
    ui_screenStateOverview = NULL;

}
